#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "Install XCode Command Line Tools:"
  xcode-select --install
  echo "Install Homebrew"
  export HOMEBREW_NO_INSTALL_FROM_API=1
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  cd /opt/homebrew/bin/
  PATH=$PATH:/opt/homebrew/bin
  cd
  touch .zshrc
  echo export PATH=$PATH:/opt/homebrew/bin >> .zshrc
  echo "Now you have Homebrew and are ready to rock and roll."
else
  echo "Cool you have Homebrew time to have some fun now"
fi

# Add this repo to one that is viewed for update
brew tap aspnet/dnx

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install the brew packages you want
brew install ack
brew install the_silver_searcher
brew install ctags
brew install htmldoc
brew install jasper
brew install libtiff
brew install ossp-uuid
brew install clamav
brew install ghostscript
brew install imagemagick
brew install jpeg
brew install little-cms
brew install pkg-config
brew install readline
brew install pidof
brew install wget
brew install pow
brew install macvim

# Install git and hub(Hub is a github specific thing allowing for things like pull-requests)
brew install git
brew install hub

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."

# Install Postgres
brew install postgresql
echo "run 'brew info postgresql' to see postgresql installation instructions. We will try the normal way."
# Add Postgres to launchctl to let OS X manage the process and start when you login, this will use the default config from /usr/local/etc/redis.conf
rm -rf /usr/local/var/postgres
mkdir /usr/local/var/postgres
initdb /usr/local/var/postgres -E utf8
mkdir -p ~/Library/LaunchAgents
ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
echo "Set default user as _postgres with no password"
createuser -a -d _postgres
echo "Finally, verify that it’s all working by connecting: psql template1 -U _postgres"
echo "sudo ARCHFLAGS="-arch x86_64" gem install pg - if having trouble installing pg up"

# Install redis
brew install redis
# Add Redis to launchctl to let OS X manage the process and start when you login, this will use the default config from /usr/local/etc/redis.conf
ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

# Install dot net stuff
brew install dnvm

# Clean up cached install files
brew cleanup
