#!/bin/sh
#
# installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
. script/homebrew
. script/cask
. script/js_packages
. script/rbenv
. script/nvmrc
. script/zshell
. osx/set-defaults.sh
